"""Shared constants used across graphragX."""

from __future__ import annotations

DEFAULT_LOGGING_LEVEL = "INFO"
DEFAULT_LOGGING_COLOR = "cyan"

OPENAI_API_KEY_ENV_NAME = "OPENAI_API_KEY"
LOGGING_LEVEL_ENV_NAME = "GRAPHRAGX_LOG_LEVEL"
LOGGING_COLOR_ENV_NAME = "GRAPHRAGX_LOG_COLOR"
WANDB_PROJECT_ENV_NAME = "WANDB_PROJECT"
WANDB_ENTITY_ENV_NAME = "WANDB_ENTITY"
WANDB_MODE_ENV_NAME = "WANDB_MODE"

DEFAULT_WANDB_PROJECT = "graphragx"
DEFAULT_WANDB_MODE = "online"

DEFAULT_TRAINING_EPOCHS = 3
DEFAULT_TRAINING_LEARNING_RATE = 1e-3
DEFAULT_TRAINING_WEIGHT_DECAY = 0.0
DEFAULT_TRAINING_LOG_EVERY = 1
DEFAULT_TRAINING_DEVICE = "auto"

DEFAULT_ANSWER_THRESHOLD = 0.5
DEFAULT_CANDIDATE_TOP_K = 10
DEFAULT_CANDIDATE_LIMIT = 15

DEFAULT_EMBEDDING_BATCH_SIZE = 1024

GNN_ANSWER_RETRIEVER_WEIGHTS_FILENAME = "gnn_answer_retriever.pt"
GNN_ANSWER_RETRIEVER_CONFIG_FILENAME = "gnn_answer_retriever_config.json"

GNN_ANSWER_RETRIEVER_EVALUATION_CONFIG_FILENAME = "evaluation_config.json"
GNN_ANSWER_RETRIEVER_EVALUATION_PREDICTIONS_FILENAME = "predictions.jsonl"

LLM_INFERENCE_REASONING_FILENAME = "reasoning.jsonl"
LLM_INFERENCE_ANSWERS_FILENAME = "answers.jsonl"
LLM_INFERENCE_CONFIG_FILENAME = "inference_config.json"

FINAL_RESULTS_CONFIG_FILENAME = "results_config.json"
FINAL_RESULTS_RETRIEVAL_METRICS_FILENAME = "retrieval_metrics.json"
FINAL_RESULTS_REASONING_METRICS_FILENAME = "reasoning_metrics.json"
FINAL_RESULTS_PER_INSTANCE_FILENAME = "per_instance_results.jsonl"

WEBQSP_NODE_EMBEDDINGS_FILENAME = "nodes.pt"
WEBQSP_RELATION_EMBEDDINGS_FILENAME = "relations.pt"
WEBQSP_QUESTION_EMBEDDINGS_FILENAME = "questions.pt"
WEBQSP_QUESTION_VOCABULARY_FILENAME = "questions.json"
WEBQSP_ENTITY_NAMES_MAPPING_PATH = "mappings/webqsp/entities_names.json"
