"""Shared pipeline foundation for graphragX."""

from pipeline.abstract import (
    AbstractStep,
    StepContext,
    StepResult,
)
from pipeline.context_builder import StepContextBuilder
from pipeline.exceptions import (
    InvalidAssistantLlmSelectionException,
    InvalidContextConstructionSelectionException,
    InvalidInteractiveConfigurationInputException,
    InvalidMainLlmSelectionException,
    InvalidSubgraphConstructionSelectionException,
    KnowledgeGraphDatasetLoadingException,
    MalformedKnowledgeGraphDatasetException,
    MissingTorchDependencyException,
    MissingTorchGeometricDependencyException,
    PipelineExecutionException,
    PipelineException,
    StepNotImplementedException,
    UnsupportedKnowledgeGraphDatasetLoaderException,
    UnsupportedKnowledgeGraphDatasetException,
)
from pipeline.models import InitialStepResult, PipelineExecutionResult
from pipeline.models import PipelineResultBank
from pipeline.pipeline import Pipeline
from pipeline.preparation import (
    BuildPipelineConfigurationStep,
    BuiltPipelineConfiguration,
    CONTEXT_CONSTRUCTION_STRATEGIES,
    ContextConstructionDefinition,
    KnowledgeGraphDatasetLoaderDefinition,
    KnowledgeGraphRawTriple,
    KNOWLEDGE_GRAPH_DATASET_CACHE_ROOT,
    KNOWLEDGE_GRAPH_DATASET_LOADERS,
    LoadKnowledgeGraphDatasetStep,
    LoadedKnowledgeGraphDataset,
    LlmModelDefinition,
    PipelineConfigurationInput,
    RECOMMENDED_ASSISTANT_LLM_MODEL_ID,
    RECOMMENDED_CONTEXT_CONSTRUCTION_STRATEGY_ID,
    RECOMMENDED_MAIN_LLM_MODEL_ID,
    RECOMMENDED_SUBGRAPH_CONSTRUCTION_ALGORITHM_ID,
    SelectKnowledgeGraphDatasetStep,
    SelectedKnowledgeGraphDataset,
    SHARED_LLM_MODELS,
    SubgraphConstructionDefinition,
    SUBGRAPH_CONSTRUCTION_ALGORITHMS,
)
from pipeline.services import (
    AbstractDatasetLoaderService,
    AbstractKnowledgeGraphDatasetProcessingService,
    AbstractService,
    KnowledgeGraphDatasetProcessingService,
    SelectionService,
    TorchGeometricKnowledgeGraphLoaderService,
)

__all__ = [
    "AbstractStep",
    "AbstractService",
    "BuildPipelineConfigurationStep",
    "BuiltPipelineConfiguration",
    "CONTEXT_CONSTRUCTION_STRATEGIES",
    "ContextConstructionDefinition",
    "InitialStepResult",
    "InvalidAssistantLlmSelectionException",
    "InvalidContextConstructionSelectionException",
    "InvalidInteractiveConfigurationInputException",
    "InvalidMainLlmSelectionException",
    "InvalidSubgraphConstructionSelectionException",
    "KnowledgeGraphDatasetLoaderDefinition",
    "KnowledgeGraphDatasetLoadingException",
    "KnowledgeGraphRawTriple",
    "KNOWLEDGE_GRAPH_DATASET_CACHE_ROOT",
    "KNOWLEDGE_GRAPH_DATASET_LOADERS",
    "LoadedKnowledgeGraphDataset",
    "LoadKnowledgeGraphDatasetStep",
    "LlmModelDefinition",
    "MalformedKnowledgeGraphDatasetException",
    "MissingTorchDependencyException",
    "MissingTorchGeometricDependencyException",
    "Pipeline",
    "PipelineConfigurationInput",
    "PipelineException",
    "PipelineExecutionException",
    "PipelineExecutionResult",
    "PipelineResultBank",
    "AbstractDatasetLoaderService",
    "AbstractKnowledgeGraphDatasetProcessingService",
    "RECOMMENDED_ASSISTANT_LLM_MODEL_ID",
    "RECOMMENDED_CONTEXT_CONSTRUCTION_STRATEGY_ID",
    "RECOMMENDED_MAIN_LLM_MODEL_ID",
    "RECOMMENDED_SUBGRAPH_CONSTRUCTION_ALGORITHM_ID",
    "SelectedKnowledgeGraphDataset",
    "SelectKnowledgeGraphDatasetStep",
    "SHARED_LLM_MODELS",
    "KnowledgeGraphDatasetProcessingService",
    "SelectionService",
    "StepContext",
    "StepContextBuilder",
    "StepNotImplementedException",
    "StepResult",
    "SubgraphConstructionDefinition",
    "SUBGRAPH_CONSTRUCTION_ALGORITHMS",
    "TorchGeometricKnowledgeGraphLoaderService",
    "UnsupportedKnowledgeGraphDatasetLoaderException",
    "UnsupportedKnowledgeGraphDatasetException",
]
